GET http://localhost:5001/posts
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWF4aW0iLCJpYXQiOjE2MTkxMTU2NjV9.ctZbJZamxEq-ajnEyaxy86pTUqEQKbUgzYAnn-GVufw

###
POST http://localhost:8080/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFrc2ltIiwiaWF0IjoxNjE4NzAyMzY5fQ.kgZbuAlb86QP1Z2tBVrzR1Xs8OO3aJazThonNo8cyUw"
    
}

###
POST http://localhost:5001/login
Content-Type: application/json

{
    "username": "Maksim"
}